import React from 'react';
import { Button } from './Button';

interface WallpaperPreviewProps {
  generatedUrl: string;
  onDownload: () => void;
  onReset: () => void;
}

export const WallpaperPreview: React.FC<WallpaperPreviewProps> = ({ generatedUrl, onDownload, onReset }) => {
  return (
    <div className="w-full max-w-6xl mx-auto animate-fade-in space-y-8">
      <div className="relative group rounded-2xl overflow-hidden shadow-2xl shadow-black/50 ring-1 ring-white/10 bg-dark-800">
        <div className="absolute top-4 left-4 z-20 px-3 py-1 bg-black/60 backdrop-blur-md rounded-full border border-white/10 text-xs font-medium text-white/80">
          16:9 Desktop Wallpaper
        </div>
        <img 
          src={generatedUrl} 
          alt="Generated Desktop Wallpaper" 
          className="w-full h-auto object-cover"
        />
        <div className="absolute inset-0 bg-gradient-to-t from-black/80 via-transparent to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300 flex items-end justify-center pb-8">
          <p className="text-white/80 text-sm font-light">Generated by Horizon Expander</p>
        </div>
      </div>

      <div className="flex flex-col sm:flex-row items-center justify-center gap-4">
        <Button onClick={onDownload} className="w-full sm:w-auto min-w-[200px]">
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={2} stroke="currentColor" className="w-5 h-5 mr-2">
            <path strokeLinecap="round" strokeLinejoin="round" d="M3 16.5v2.25A2.25 2.25 0 005.25 21h13.5A2.25 2.25 0 0021 18.75V16.5M12 9.75l-4.5 4.5m0 0l4.5 4.5m-4.5-4.5h10.5" />
          </svg>
          Download Wallpaper
        </Button>
        <Button onClick={onReset} variant="secondary" className="w-full sm:w-auto">
          Create Another
        </Button>
      </div>
    </div>
  );
};
